// ── Types ────────────────────────────────────────────────────────────
export type {
  Json,
  Database,
  Tables,
  Enums,
  Partner,
  PartnerContact,
  Profile,
  Product,
  ProductAsset,
  ProductPrice,
  OrderRequest,
  OrderRequestItem,
  InventoryStatus,
  InventoryMovement,
  Document,
  ClientDistributor,
  Invoice,
  KPIManualEntry,
  PricingMode,
  SupplierCurrency,
  FreightMode,
  VolumeTier,
  PricingInputs,
  PricingResult,
  PricingSystemSetting,
  Prospect,
  CRMInteraction,
  CRMStatus,
  VenueType,
  CRMInteractionType,
  UserRole,
  OrderStatus,
  PartnerType,
  ProductCategory,
  DocumentType,
  DocumentAudience,
  InventoryStatusEnum,
  ProductAssetType,
  InvoiceStatus,
} from "./types";

// ── Constants ────────────────────────────────────────────────────────
export {
  ACTIVE_ORDER_STATUSES,
  ORDER_STATUS_LABELS,
  ORDER_STATUS_COLORS,
  INVENTORY_STATUS_LABELS,
  PARTNER_TYPE_LABELS,
  USER_ROLE_LABELS,
  PRODUCT_CATEGORIES,
  DOCUMENT_TYPES,
  DOCUMENT_TYPE_LABELS,
  DOCUMENT_CATEGORIES,
  DOCUMENT_CATEGORY_LABELS,
  DOCUMENT_CATEGORY_DESCRIPTIONS,
  DOCUMENT_TYPE_TO_CATEGORY,
  DOCUMENT_STATUSES,
  DOCUMENT_STATUS_LABELS,
  DOCUMENT_AUDIENCES,
  DOCUMENT_AUDIENCE_LABELS,
  CONTRACT_TYPES,
  CONTRACT_TYPE_LABELS,
  CLIENT_TIERS,
  CLIENT_TIER_LABELS,
  CAPACITY_STATUSES,
  CAPACITY_STATUS_LABELS,
  INVOICE_STATUSES,
  INVOICE_STATUS_LABELS,
  INVOICE_STATUS_COLORS,
  INVENTORY_ADJUSTMENT_TYPES,
  INVENTORY_ADJUSTMENT_LABELS,
  VENUE_TYPES,
  VENUE_TYPE_LABELS,
} from "./constants";

export type {
  ActiveOrderStatus,
  ContractType,
  ClientTier,
  CapacityStatus,
  InventoryAdjustmentType,
  DocumentCategory,
  DocumentStatus,
} from "./constants";




